package ryanwizz.usecases.mybatis.dao;

import ryanwizz.usecases.mybatis.model.Flight;

import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper

public interface FlightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Mon May 08 16:04:12 EEST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Mon May 08 16:04:12 EEST 2017
     */
    int insert(Flight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Mon May 08 16:04:12 EEST 2017
     */
    Flight selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Mon May 08 16:04:12 EEST 2017
     */
    List<Flight> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FLIGHT
     *
     * @mbg.generated Mon May 08 16:04:12 EEST 2017
     */
    int updateByPrimaryKey(Flight record);
}